const PDFDocument = require('pdfkit');
const bwipjs = require('bwip-js');

function createPdf(doc, title, subtitle) {
  doc.image('public/images/logo1.png', doc.page.width / 2 - 40, 40, { width: 80 });
  doc.moveDown(2);
  doc.fontSize(16).font('Helvetica-Bold').fillColor('#003366').text('Republic of Somaliland', { align: 'center' });
  doc.fontSize(14).font('Helvetica').fillColor('#003366').text('Unified Justice System', { align: 'center' });
  doc.moveDown(2);

  doc.fontSize(12).font('Helvetica-Bold').fillColor('#003366').text(title, { align: 'center', underline: true });
  if (subtitle) {
    doc.fontSize(12).font('Helvetica').fillColor('#003366').text(subtitle, { align: 'center' });
  }
  doc.moveDown();
}

function addBarcode(doc, text) {
  return new Promise((resolve, reject) => {
    bwipjs.toBuffer({
      bcid: 'code128',
      text: text,
      scale: 3,
      height: 10,
      includetext: true,
      textxalign: 'center',
    }, (err, png) => {
      if (err) {
        reject(err);
      } else {
        doc.image(png, {
          fit: [250, 100],
          align: 'center',
          valign: 'center'
        });
        resolve();
      }
    });
  });
}

function addFooter(doc) {
  const totalPages = doc.bufferedPageRange().count;
  for (let i = 0; i < totalPages; i++) {
    doc.switchToPage(i);
    doc.fontSize(8).fillColor('gray').text(
      'This document is generated by the Unified Justice System of the Republic of Somaliland. Unauthorized use or duplication is prohibited.',
      50,
      doc.page.height - 50,
      { align: 'center' }
    );
    doc.text(
      `Page ${i + 1} of ${totalPages}`,
      50,
      doc.page.height - 35,
      { align: 'right' }
    );
  }
}

module.exports = { createPdf, addBarcode, addFooter };
